FROM nixorg/nix:latest

####################### Install dependencies #######################

RUN mkdir -p /etc/nix && echo 'sandbox = false' > /etc/nix/nix.conf
RUN nix-channel --add https://nixos.org/channels/nixos-19.03 nixpkgs
RUN nix-channel --update
RUN nix-env -iA nixpkgs.stack nixpkgs.coreutils nixpkgs.lessc nixpkgs.findutils nixpkgs.redis nixpkgs.nodejs-10_x

####################### Configure the project #######################

# Copy project configuration files
COPY stack.yaml /lojto/stack.yaml
COPY lojto.cabal /lojto/lojto.cabal

# Setup GHC
RUN cd /lojto && stack setup

# Install dependencies
COPY haskell/libs /lojto/haskell/libs
RUN cd /lojto && stack install --only-dependencies

# Copy source code
COPY haskell /lojto/haskell
COPY LICENSE /lojto/LICENSE

# Copy resources
COPY resources /lojto/resources

# Compile source code and documentation
RUN cd /lojto && stack haddock --no-haddock-deps --haddock-internal

# Move documentation
RUN mv /lojto/.stack-work/install/x86_64-linux-nix/*/*/doc /lojto/doc

# Copy audio files
COPY static/audio /lojto/static/audio

# Copy image files
COPY static/images /lojto/static/images

# Copy pwa files
COPY static/pwa /lojto/static/pwa

# Copy assets
COPY assets /lojto/assets

# Copy buildscripts
COPY buildscripts /lojto/buildscripts

# Generate stylesheet files
RUN cd /lojto && LOJBAN_TOOL_BYPASS_NIX=true ./buildscripts/make-css.sh

# Generate javascript files
RUN cd /lojto && LOJBAN_TOOL_BYPASS_NIX=true ./buildscripts/make-javascript.sh

####################### Expose ports #######################
EXPOSE 8000/tcp

####################### Default command #######################
CMD echo "hosts: files dns" > /etc/nsswitch.conf && (redis-server >/dev/null 2>/dev/null &) && cd /lojto && .stack-work/install/x86_64-linux-nix/*/*/bin/server
