#!/usr/bin/env bash
set -e

# Function to run commands inside a Nix shell
run_command(){
    nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-23.11.tar.gz "./buildscripts/environments/haskell.nix" --run "$1"
}

COMMAND="haskell-language-server-wrapper "$(printf "%q " "$@")""

#LOJBANIOS_BYPASS_NIX="" # Never bypass nix
if [[ -n "$LOJBANIOS_BYPASS_NIX" ]]; then
    echo "--> Runing: $COMMAND"
    $COMMAND
else
    # Setup nix-shell environment
    echo "--> Step 1 - Preparing nix-shell environment..."
    run_command ""

    # Run stack command
    echo "--> Step 2 - Runing: $COMMAND"
    run_command "$COMMAND"
fi
