#!/usr/bin/env bash
set -e

# Function to run commands inside a Nix shell
run_command(){
    # nixos-23.05's version of haskell-language-server doesn't support ghc-8.8.4, so we need to use nixos-22.11 instead
    nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-22.11.tar.gz "./buildscripts/environments/haskell.nix" --run "$1"
}

COMMAND="haskell-language-server-8.8.4"

LOJBANIOS_BYPASS_NIX="" # Never bypass nix
if [[ -n "$LOJBANIOS_BYPASS_NIX" ]]; then
    echo "--> Runing: $COMMAND"
    $COMMAND
else
    # Setup nix-shell environment
    echo "--> Step 1 - Preparing nix-shell environment..."
    run_command ""

    # Run stack command
    echo "--> Step 2 - Runing: $COMMAND"
    run_command "$COMMAND"
fi
