#!/usr/bin/env bash
set -e

# Identify the directory where this script is located
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Update PATH (so that 'haskell-language-server-with-custom-ghc' is found)
export PATH="$DIR":$PATH

# Function to run commands inside a Nix shell
run_command(){
    nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-23.05.tar.gz "./buildscripts/environments/haskell.nix" --run "$1" --keep LOJBANIOS_ENVIRONMENT --keep LOJBANIOS_OAUTH2_GOOGLE_CLIENT_ID --keep LOJBANIOS_OAUTH2_GOOGLE_CLIENT_SECRET --keep LOJBANIOS_OPENID_MICROSOFT_CLIENT_ID --keep LOJBANIOS_OPENID_MICROSOFT_CLIENT_SECRET --keep LOJBANIOS_REDIS_HOSTNAME
}

COMMAND="haskell-language-server-with-custom-ghc"

LOJBANIOS_BYPASS_NIX="" # Never bypass nix
if [[ -n "$LOJBANIOS_BYPASS_NIX" ]]; then
    echo "--> Runing: $COMMAND"
    $COMMAND
else
    # Setup nix-shell environment
    echo "--> Step 1 - Preparing nix-shell environment..."
    run_command ""

    # Run stack command
    echo "--> Step 2 - Runing: $COMMAND"
    run_command "$COMMAND"
fi
